server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: drop-shot-matching
  datasource:
    url: "jdbc:h2:file:./data/drop-shot;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS dropshot\\;SET SCHEMA dropshot"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/dropshot?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=utf8&useUnicode=true}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
